### ISSUE TITLE
REMORA fails in TACC resources for users with default shell csh

### ISSUE THREAD

**Issue by carlosrosales** [TACC/remora#14]
Users with default csh shells in Stampede and Lonestar 5 are unable to collect data. At this moment I am unsure if this is due to TACC's non-standard startup behavior, or if this is a more general issue. I will test on a system with standard startup scripts and then investigate the issue. Right now this is affecting a very limited number of REMORA users, but it should still be addressed.

**Comment by crookscj** [comment]
We can  duplicate this problem at BP.  Our csh users cannot collect data, but bash users can.  We have tried this  using the same submit script.  Most of our users are csh users.  

Has there been any further work/investigation of this?

Thanks.
Cindy Crooks

**Comment by antoniogi** [comment]
Cindy,

Not yet. We have been working on adding new features. This is next in our list.

**Comment by carlosrosales** [comment]
Someone from UNC contacted me recently with a suggestion on how to fix this. Let me search my email and see if it is something we can implement for a 1.7.1 patch or release.

**Comment by crookscj** [comment]
Thank you.

**Comment by carlosrosales** [comment]
This has been fixed in 1.7.1, thanks to suggestions from Mark Reed at UNC.

**Comment by crookscj** [comment]
Thank you.

**Comment by crookscj** [comment]
I built the 1.7.1 version here this morning.  It appears to be working for the users with csh.  Once user observed that the memory reports were output only in html, there were no png files.  Is that to be expected?

Thank you for your help.

Cindy

**Comment by antoniogi** [comment]
That's right. Version 1.7+ automatically generates plots at the end of the execution of the code in html format. Users can still generate pngs by running the remora_post command.

**Comment by crookscj** [comment]
I believe “remora_post” was run, but the png files were not generated for memory.

**Comment by antoniogi** [comment]
I'll have a look at this. I kind of want to deprecate the postprocessing tool and simply provide the html graphs. Is there a reason why that doesn't work for you? It is possible to generate both html and pngs on the fly, but the html version offers some interaction that makes results easier to understand on many-core architectures.

**Comment by antoniogi** [comment]
Cindy,

I fixed a bunch of bugs on the remora_post script. It should work again if you pull the repo. It's still not part of any tag as we are working on the next minor release. Moving forward, the script will not be maintained because it creates some issues for us (having initialization, collection and postprocessing integrated in the modules is easier for us and other developers). We'll consider adding the option to generate pngs on the fly as well as htmls.

**Comment by crookscj** [comment]
Antonio,

Thanks for the fixes in remora_post.  It appears to be working fine here.

I asked the user about the html/png files.  She says she can work with the html.

Cindy
