### ISSUE TITLE
Make Remora configurable

### ISSUE THREAD

**Issue by antoniogi** [TACC/remora#2]
Many information about Stampede is hardcoded in Remora. This needs to be changed (config files?) so that it can be easily installed somewhere else.

**Comment by carlosrosales** [comment]
Is there much apart from the xltop port and the variable names? I think
most of the rest is not TACC specific.

**Comment by antoniogi** [comment]
At least the postprocessing Python stuff.

**Comment by carlosrosales** [comment]
Oh yeah... Forgot about that, sorry...

**Comment by carlosrosales** [comment]
I've removed all TACC_ strings from the source and performed a brief test. All seems to be working OK. I have also added support for SGE (besides SLURM) and remora now generates an error if an unknown scheduler is used.

We still need to improve the file system processing to avoid hard-coded strings, but this should now be portable in "BASIC" mode.

**Comment by boegel** [comment]
In what way is the preprocessing stuff TACC specific? Because `install.sh` does a `module load python` followed by `pip install blockdiag`? Any other reason?

@carlosrosales: can you point me to some info on adding support for another resource manager (e.g. a commit ID)? I'm very interested in adding support for PBS.

**Comment by antoniogi** [comment]
Kenneth,

The postprocessing uses Python (matplotlib) for plotting the data. We then also need blockdiag to generate a diagram with the nodes and switches used during the job. We still need to work on this and see if we can remove this dependency. 

About PBS. I'm working on a new version of Remora that should make easier to navigate through the code (I'll commit the changes in a couple of hours to a new branch). Right now, look at lines 95 to 106 of the remora script.

**Comment by boegel** [comment]
@antoniogi: thanks for the info, I'll try and take a look at the reworked version of Remora, spending time with the current version is probably not worth the effort (I've just started exploring REMORA)

**Comment by antoniogi** [comment]
@boegel Sounds good. We are trying to have a new release ready before Christmas.

**Comment by boegel** [comment]
@antoniogi: any overview of the major changes available already? ;-)

**Comment by antoniogi** [comment]
We haven't decided yet. We are refactoring the code as it was already a bit messy.

**Comment by carlosrosales** [comment]
Mostly modularization, automated network device capture and independence
from xltop for luster data. Looks like we may get some help to add gpfs as
well. We are trying to make it easier to deploy and extend :)

On Tuesday, December 8, 2015, Kenneth Hoste notifications@github.com
wrote:

> @antoniogi https://github.com/antoniogi: any overview of the major
> changes available already? ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TACC/remora/issues/2#issuecomment-163036185.

## 

GUE Tech I Diver
Slow is smooth, smooth is fast

**Comment by boegel** [comment]
If you have support for GPFS, I'm all in for testing it (we don't have Lustre, we're all GPFS and NFS over GPFS).

**Comment by carlosrosales** [comment]
Not yet, we just have someone that has offered to help. I don't expect that
will be ready until next year.

**Comment by antoniogi** [comment]
@boegel You can check the scheduler functionality in the src/aux/scheduler script. You can make changes there. Right now the variable that we really need is NODES, but we set a couple more in case we need them at some point.

**Comment by antoniogi** [comment]
All the modules have been reimplemented. We now use a configuration file.

Closing this issue.

**Comment by boegel** [comment]
Does this conclude the refactoring you were working on, or should I hold off a bit longer taking a detailed look at getting this set up at my site?

**Comment by antoniogi** [comment]
Almost. We just need to run some tests to check that everything works as expected. There's no XLTOP anymore, and all the data collection has been moved to the modules folder. There's a configuration file that specifies the tests that are available on each site (simply add/remove things in the text file and done). RIght now we support lustre, but it you want to add something else, feel free to do it. Simply create a new script in the modules folder (let's say mytest), and then, in the config file, add the line mytest. In the mytest script, you have to have the same methods that you can see in all the other modules (simply renamed to finish with _mytest). And that's it. We still have to write the documentation for this. Any input is more than welcome. 

PS.- The postprocessing part (python script that create plots) is not modular at all. We have left that part out for now.
