### ISSUE TITLE
Support for other mlx_# interfaces

### ISSUE THREAD

**Issue by kmanalo** [TACC/remora#23]
I recall 'mlx_4' being hard-wired into paths
In our newer system, we have 'mlx_5' for EDR.

Is there a place where one can discover the IB interface using something like

```
ibstat | head -n 1 | awk '{print $2}' | tr -d "'"
```

And applying this in the right spots?

Thanks,
Kevin
OSC

**Comment by carlosrosales** [comment]
Yes, this is a simple change. I should have time to add this and a couple
of other suggestions to the master branch next week. Thanks for the
suggestion!!

Carlos

**Comment by kmanalo** [comment]
I should add that obviously there are no problems when I change to mlx_5.
Nice tool to check on IB network activity with an application.

Thanks!
Kevin

**Comment by antoniogi** [comment]
This has been implemented and it's available in the master branch. Release coming soon.
