### ISSUE TITLE
Define where the modules are installed using an environment variable

### ISSUE THREAD

**Issue by antoniogi** [TACC/remora#5]
The idea is that a variable will store a path, or set of paths, where modules can be found. That way users can easily extend the functionality of the tool once it has been installed in the system.

**Comment by carlosrosales** [comment]
Do you think the modules should have multiple possible locations? Otherwise
I think that $REMORA_BIN/modules should be sufficient, right?

On Thu, Jan 7, 2016 at 8:54 AM, Antonio Gómez notifications@github.com
wrote:

> The idea is that a variable will store a path, or set of paths, where
> modules can be found. That way users can easily extend the functionality of
> the tool once it has been installed in the system.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TACC/remora/issues/5.

## 

GUE Tech I Diver
Slow is smooth, smooth is fast

**Comment by antoniogi** [comment]
I was thinking of having a system-wide installation. Then, users can add new modules by passing a path where the modules can be found. We also need to, somehow, use a new configuration file that is not the default one. Nothing critical right now.

**Comment by carlosrosales** [comment]
Good idea, we can have a REMORA_MODULE_PATH or REMORA_PLUGIN_PATH that we use to search for new additions.

**Comment by antoniogi** [comment]
Used REMORA_MODULE_PATH
