### ISSUE TITLE
How to get stat when job is killed

### ISSUE THREAD

**Issue by tahia** [TACC/remora#54]
Hi 
Is there any way to get the remora stat if the job is killed? I can see the memory and CPU usage files are there. Any way to parse it? 

Best,
Taslima

**Comment by carlosrosales** [comment]
Hi, 

You should be able to run "remora_post_crash jobid" to recover the files and generate the summary data. This should be described in section 2 of the user guide if I remember correctly. 

Best,
Carlos

**Comment by tahia** [comment]
Thanks Carlos! It works. 

Best,
Taslima

**Comment by tahia** [comment]
Hi Carlos
One of my job was killed due to time limit so I run remora_post_crash and got the summary html files. Unfortunately the file for cpu is ~30 Mb and I can not open this with any browser. Any idea how to open or parse that file? I need to know my maximum cpu usage.

Best,
Taslima
