### ISSUE TITLE
How can we integrate something like https://github.com/nnnick/Chart.js in REMORA

### ISSUE THREAD

**Issue by antoniogi** [TACC/remora#8]
I like the plots that it generates. Can we generate the html and the data so that users can download a tar/zip file and visualize the results in their own machines using a web browser?

**Comment by carlosrosales** [comment]
I like this, too. I'm sure we can figure out a way to do this. It would be a great way to implement a real time monitoring system or simply a full run report.

**Comment by antialamas** [comment]
I like it. I am going to start playing with it! Not just for remora data but some of the other stats we produce.

**Comment by antoniogi** [comment]
Using Google Chart for this. Results look nice and it's easy to implement (but boring).
